# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Javier Querol
tagline:          The Jekyll Butler
url:              http://javierquerol.es
paginate:         1
baseurl:          http://JavierQuerol.github.io/poole/
author:
  name:           Javier Querol
  url:            https://twitter.com/javierquerol
  email:          querol.javi@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/javierquerol/poole
